parameters:
    buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Compilando proyecto para ${{parameters.buildConfiguration}}'
  inputs:
    command: 'build'
    arguments: '--configuration=${{parameters.buildConfiguration}} --no-restore'
    projects: 'Tailspin.SpaceGame.Web/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Compilando proyecto para ${{parameters.buildConfiguration}}'
  inputs:
    command: 'publish'
    projects: 'Tailspin.SpaceGame.Web/*.csproj'
    publishWebProjects: false
    arguments: '--no-build --configuration=${{parameters.buildConfiguration}} --output=$(Build.ArtifactStagingDirectory)/${{parameters.buildConfiguration}}'
    zipAfterPublish: true